url: "http://www.westhousehotelnewyork.com"

# Build settings
default_lang: 'en'
languages: ['en']

exclude: ['sitemap.json'] 

page_gen:
  - data: 'events'
    template: 'tmp-calendar-more'
    dir: 'calendar-more'
  - data: 'blog'
    template: 'tmp-blog-more'
    dir: 'blog-details'
